import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Physical AI & Humanoid Robotics book
  physicalAISidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'ros2/chapter-1-middleware',
        'ros2/chapter-2-nodes-topics-services',
        'ros2/chapter-3-rclpy-bridge',
        'ros2/chapter-4-urdf-humanoids'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin/chapter-1-introduction',
        'digital-twin/chapter-2-physics-simulation',
        'digital-twin/chapter-3-environment-modeling',
        'digital-twin/chapter-4-unity-simulation',
        'digital-twin/chapter-5-sensor-simulation'
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'ai-robot-brain/chapter-1-ai-role',
        'ai-robot-brain/chapter-2-isaac-sim',
        'ai-robot-brain/chapter-3-synthetic-data',
        'ai-robot-brain/chapter-4-isaac-ros',
        'ai-robot-brain/chapter-5-navigation-nav2'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'vla/chapter-1-language-to-action',
        'vla/chapter-2-voice-to-action',
        'vla/chapter-3-cognitive-planning',
        'vla/chapter-4-vision-language-grounding',
        'vla/chapter-5-capstone-project'
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'hardware-lab-setup',
        'weekly-learning-plan',
        'references'
      ],
    }
  ],
};

export default sidebars;
